### ISSUE TITLE
Improve configure to use system-wide installed samtools

### ISSUE THREAD

**Issue by mmokrejs** [iontorrent/TS#14]
Hi,
  could you please add to your configure a check for a system-wide samtools installation? It seems your build system requires a local copy of samtools sources in the parent directory. Just include bam.h and use -I argument to compiler to find it.

<pre>
>>> Compiling source in /mnt/1TB/var/tmp/portage/sci-biology/tmap-9999/work/tmap-9999 ...
make -j2 
make  all-recursive
make[1]: Entering directory '/mnt/1TB/var/tmp/portage/sci-biology/tmap-9999/work/tmap-9999'
Making all in .
make[2]: Entering directory '/mnt/1TB/var/tmp/portage/sci-biology/tmap-9999/work/tmap-9999'
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.     -O2 -pipe -maes -mpclmul -mpopcnt -mavx -march=native -Wall -g -O3 -pthread -msse3 -D_TMAP_BWT_RUN_TYPE=0 -D_USE_KNETFILE -Isrc/samtools -DSAMTOOLS_MAIN -c -o src/sw/tmap_vsw_bm.o src/sw/tmap_vsw_bm.c
make[2]: *** No rule to make target 'src/samtools/bam.c', needed by 'src/samtools/bam.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
In file included from src/sw/tmap_vsw_bm.c:8:0:
src/sw/../util/tmap_sam_convert.h:6:29: fatal error: ../samtools/bam.h: No such file or directory
 #include "../samtools/bam.h"
                             ^
compilation terminated.
Makefile:1285: recipe for target 'src/sw/tmap_vsw_bm.o' failed
make[2]: *** [src/sw/tmap_vsw_bm.o] Error 1
</pre>

Here are the files I have installed:

<pre>
...
/usr/include/bam/bam.h
/usr/include/bam/bam2bcf.h
/usr/include/bam/bam_endian.h
/usr/include/bam/bam_lpileup.h
/usr/include/bam/bam_plbuf.h
/usr/include/bam/bam_tview.h
/usr/include/bam/errmod.h
/usr/include/bam/kprobaln.h
/usr/include/bam/sam.h
/usr/include/bam/sam_header.h
/usr/include/bam/sample.h
/usr/include/bam/samtools.h
/usr/include/bam/stats_isize.h
/usr/include/bam/version.h
...
/usr/lib64/libbam.so -> libbam.so.1.0
/usr/lib64/libbam.so.0 -> libbam.so.1.0
/usr/lib64/libbam.so.1.0
</pre>

**Comment by jmanning2k** [comment]
TMAP doesn't use the stock samtools library, but uses a custom fork of samtools. This fork is from the same original author as TMAP and adds features around BAM header creation, something the main samtools branch does poorly.  (Coincidentally, the original author of both TMAP and this samtools fork is now a core developer for samtools - but has not integrated the changes from this fork.)

I know TMAP fails without the BAM header extensions, and in any case, I'm not sure TMAP would be compatible with the current htslib-based samtools package. It needs a pre-1.0 version of samtools.

You can download the correct fork of samtools at: https://github.com/nh13/samtools
You must place this in the src/samtools/ directory, and then run a clean build with: ``make distclean; ./autogen.sh; ./configure -C; make``.  You do not need to build samtools separately, the TMAP script will drive the build with the appropriate settings.

That said, I just tried this and it still fails. I don't think the Makefile portions have been updated with recent changes to TMAP, since it is built using CMake now. You will have a much easier time if you can build TMAP using the CMake system. (Note that the CMake build will fetch and build the appropriate samtools library for you.)

I'm playing with Makefile.in and some include changes in the hopes I can revive the standalone build. I will let you know if I make any progress there, but I'm not optimistic.

**Comment by nh13** [comment]
@jmanning2k: I am not a core developer for samtools and the changes I made have been considered by the developers of samtools (and htslib) to be included in a future release, but it is not high priority.

**Comment by mmokrejs** [comment]
Hi, thank you for clarifications. Maybe this is a good chance to ping the htslib/samtools developers?
