### ISSUE TITLE
build steps incomplete

### ISSUE THREAD

**Issue by Aargol** [iontorrent/TS#36]
@iontorrent-dev  while i'm trying to compile TVC following REAME file from the link you provide
http://updates.iontorrent.com/tvc_standalone/README*
i found step 6 and step 9 are missing in  versions 5.xx.xx of TS. Can someone explain why and offer some nice guidance?  thanks :D

**Comment by chenliangomc** [comment]
According to [v4.6.0 ReadMe](http://updates.iontorrent.com/tvc_standalone/README_4.6.0.txt), step 6 is build vcftools, and step 9 is build/install GATK.

**Comment by ipan** [comment]
In TSS 5.x, we have removed the GATK dependency. That's why the instructions would be different.

Please see this for list of the links for tvc standalone for 5.x releases:

http://updates.iontorrent.com/tvc_standalone/

I would recommend to run docker image for build.  The example is for *centos7* and should product a tar.gz file like this: `tvc-5.8.0-CentOS_7.3.1611_x86_64-binary.tar.gz`.

```
wget http://updates.iontorrent.com/tvc_standalone/tvc-5.8.0.tar.gz
tar xvf tvc-5.8.0.tar.gz
docker run -t -v $(pwd):/src iontorrent/tvcbuild:centos7 bash -c 'build.sh tvc-5.8.0'
```

You can build with *trusty*, *xenial*, and *jesse*.
